name: Test templates on main and PRs
on:
  push:
    branches: [main]
    paths:
      - .github/test-templates-on-main-and-prs.yml
      - src/**
      - test/**
      - tools/test.sh
      - tools/instantiate-template.js
  pull_request:
    branches: [main]
    paths:
      - .github/test-templates-on-main-and-prs.yml
      - src/**
      - test/**
      - tools/test.sh
      - tools/instantiate-template.js
concurrency:
  group: test-templates-on-main-and-prs-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-templates-on-main-and-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g @devcontainers/cli
      - run: tools/test.sh
